export const homeObjFive = {
  primary: false,
  lightBg: true,
  imgStart: "start",
  lightTopLine: false,
  lightTextDesc: false,
  lightText: false,
  buttonLabel: "Get Started",
  description: "Five",
  headline: "Lead Generation Specialist for Online Businesses.",
  topLine: "Marketing Agency",
  img: require("../../images/codeimg4.png"),
  alt: "Image",
  start: "true",
};
